variables:
  GTEST_COLOR: "yes"


build:
  parallel:
    matrix:
      - COMPILER: gcc
        VERSION: [14, 13]
      - COMPILER: clang
        VERSION: [18, 17]
  image: registry.gitlab.com/offa/docker-images/${COMPILER}:${VERSION}
  script:
    - script/ci_setup.sh
    - script/ci_build.sh -asan -ubsan

coverage:
  image: registry.gitlab.com/offa/docker-images/gcc:14
  script:
    - script/ci_setup.sh
    - script/ci_build.sh -cov
  coverage: /^\s*lines:\s*\d+.\d+\%/

formatting:
  image: docker:latest
  variables:
    CLANGFORMAT_VERSION: 17
  services:
    - docker:dind
  before_script:
    - apk add --no-cache git
    - git clone --depth=1 https://github.com/DoozyX/clang-format-lint-action.git
    - docker build -t clang-format-lint clang-format-lint-action
  script:
    - docker run --rm --workdir /src -v ${PWD}:/src clang-format-lint --clang-format-executable /clang-format/clang-format${CLANGFORMAT_VERSION} -r --exclude .git .
